# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" zsh
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new -A -s main

bindd = SUPER, E, File manager, exec, uwsm-app -- nautilus --new-window

bindd = SUPER, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, B, Browser (private), exec, omarchy-launch-browser --private

bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus PIPEWIRE_LATENCY="128/48000" reaper

bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, N, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"

bindd = SUPER, A, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, A, Docker, exec, omarchy-launch-tui lazydocker
 
unbind = SUPER, P
bindd = SUPER, P, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER, D, Discord, exec, omarchy-launch-or-focus-webapp Discord "https://discord.com/channels/@me"
bindd = SUPER SHIFT, D, Zoom, exec, omarchy-launch-or-focus-webapp Zoom "https://dhbw-stuttgart.zoom.us/join"

unbind = SUPER, W #Unbind closing app
bindd = SUPER, W, Email, exec, omarchy-launch-or-focus thunderbird
bindd = SUPER SHIFT, W, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"

bindd = SUPER, R, OpenWebUi, exec, omarchy-launch-webapp "http://truenas:31028"
bindd = SUPER SHIFT, R, Gemini, exec, omarchy-launch-webapp "https://claude.ai"



bindd = SUPER, Q, Close window, killactive,

bindd = SUPER, mouse:275, Switch to workspace 1, workspace, 1
bindd = SUPER, mouse:276, Switch to workspace 2, workspace, 2
bindd = SUPER, page_down, Switch to workspace 3, workspace, 3
bindd = SUPER, page_up, Switch to workspace 4, workspace, 4

bindd = SUPER SHIFT, mouse:275, Move window to workspace 1, movetoworkspace, 1
bindd = SUPER SHIFT, mouse:276, Move window to workspace 2, movetoworkspace, 2
bindd = SUPER SHIFT, page_down, Move window to workspace 3, movetoworkspace, 3
bindd = SUPER SHIFT, page_up, Move window to workspace 4, movetoworkspace, 4


unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L

bind = SUPER, H, movefocus, l
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u
bind = SUPER, L, movefocus, r

bind = SUPER SHIFT, H, swapwindow, l
bind = SUPER SHIFT, J, swapwindow, d
bind = SUPER SHIFT, K, swapwindow, u
bind = SUPER SHIFT, L, swapwindow, r

bindd = SUPER, odiaeresis, Toggle window split, layoutmsg, togglesplit
