unbind C-b
set -g prefix C-Space

unbind r
bind r source-file ~/.tmux.conf

bind J split-window -v
bind L split-window -h

unbind h
unbind j
unbind k
unbind l

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g mouse on

set-option -g status-position top
