set -g prefix C-Space

unbind ^
bind ^ source-file ~/.tmux.conf

setw -g mode-keys vi

set -g mouse on

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark256'
set -g @tmux-gruvbox-right-status-x '%d.%m.%Y'
# set -g @plugin 'odedlaz/tmux-onedark-theme'
# set -g @onedark_date_format "%d.%m.%y"

set -g @plugin 'christoomey/vim-tmux-navigator'

#Split vertically / horizontally
bind-key -n -r M-s split-window -v -c "#{pane_current_path}"
bind-key -n -r M-v split-window -h -c "#{pane_current_path}"

# New Window / Session
bind-key -n -r M-c new-window -c "#{pane_current_path}"
bind-key -n -r M-C command-prompt -p "New Session:" "new-session -A -s '%%'"

#Navigate to tabs
bind-key -n -r M-1 select-window -t 1
bind-key -n -r M-2 select-window -t 2
bind-key -n -r M-3 select-window -t 3
bind-key -n -r M-4 select-window -t 4
bind-key -n -r M-5 select-window -t5
bind-key -n -r M-6 select-window -t 6
bind-key -n -r M-7 select-window -t 7
bind-key -n -r M-8 select-window -t 8
bind-key -n -r M-9 select-window -t 9

#Killing windows / panes / sessions
bind-key -n -r M-x kill-pane
bind-key -n M-x if-shell "[ #{pane_current_command} != bash ] && [ #{pane_current_command} != zsh ]" \
  "confirm-before -p 'kill pane? (y/n)' kill-pane" \
  "kill-pane"
bind-key -n -r M-X confirm-before -p "Kill window #W? (y/n)" kill-window
bind-key -n -r M-q confirm-before -p "Kill session #W? (y/n)" kill-session

#Detatch from tmux
bind-key -n -r M-Q detach-client

#Search for links and open them in fzf
bind-key -n M-o split-window -v -l 20 \
  "tmux capture-pane -J -p -t '{last}' | grep -oE '(https?):\/\/[^ >\"]+' | sort -u | fzf --multi --bind 'alt-a:select-all,alt-d:deselect-all' | xargs -r open"

#Manage / switch sessions
bind-key -n M-d choose-tree -Zs
bind-key -n -r M-D switch-client -l

#Resize windows
bind-key -n -r M-h resize-pane -L 5
bind-key -n -r M-l resize-pane -R 5
bind-key -n -r M-j resize-pane -D 5
bind-key -n -r M-k resize-pane -U 5

set -g base-index 1
set-option -g renumber-windows on

set -g status-position top

set-option -g detach-on-destroy off

run '~/.tmux/plugins/tpm/tpm'
